server.port=${PORT:8080}
logging.level.com.javaesencial.biblioteca=WARN

biblioteca.nombre=Biblioteca Municipal "El Quijote"
biblioteca.version=2.0
biblioteca.max-libros=500
biblioteca.modo-mantenimiento=false
