server.port=${PORT:8080}
logging.level.com.javaesencial.biblioteca=WARN

biblioteca.nombre=Biblioteca Municipal "El Quijote"
biblioteca.version=2.0
biblioteca.max-libros=500
biblioteca.modo-mantenimiento=false

spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=biblioteca_user
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
