spring.application.name=biblioteca-spring
spring.profiles.active=dev

springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs

jwt.secreto=cambia-este-secreto-en-produccion-biblioteca-jwt-2026
jwt.expiracion-ms=3600000

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized

info.app.nombre=biblioteca-spring
info.app.version=1.0.0
info.app.descripcion=API REST de la Biblioteca Municipal «El Quijote»
