spring.application.name=biblioteca-spring
spring.profiles.active=dev

springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs

jwt.secreto=cambia-este-secreto-en-produccion-biblioteca-jwt-2026
jwt.expiracion-ms=3600000
