-- V1: esquema inicial (libro, usuario, prestamo).
-- Sintaxis SQL estándar (IDENTITY, no AUTO_INCREMENT/SERIAL) para que
-- el mismo script valga en H2 2.x (dev) y PostgreSQL 16 (prod) sin
-- tocar una línea. Una vez aplicado, este script es INMUTABLE: los
-- cambios posteriores van en V2, V3... nunca reescribiendo este.

CREATE TABLE libro (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor  VARCHAR(255) NOT NULL,
    anio   INTEGER NOT NULL
);

CREATE TABLE usuario (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    email  VARCHAR(255) NOT NULL
);

CREATE TABLE prestamo (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id       BIGINT NOT NULL REFERENCES usuario(id),
    libro_id         BIGINT NOT NULL REFERENCES libro(id),
    fecha_prestamo   DATE,
    fecha_devolucion DATE
);

CREATE INDEX idx_prestamo_usuario ON prestamo(usuario_id);
CREATE INDEX idx_prestamo_libro ON prestamo(libro_id);
