-- V3: cuenta de acceso a la API, separada de "usuario" (el socio).

CREATE TABLE credencial (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    rol      VARCHAR(20) NOT NULL
);
