### Java Esencial -- Volumen 2 -- peticiones de prueba
### Se amplía capítulo a capítulo (caps. 2, 5, 6, 10, 11, 13, 14).

### Capítulo 2 -- primeras peticiones
GET http://localhost:8080/hola

###
GET http://localhost:8080/libro-ejemplo

### Capítulo 5 -- CRUD completo de libros
GET http://localhost:8080/libros

###
GET http://localhost:8080/libros/1

###
POST http://localhost:8080/libros
Content-Type: application/json

{
  "titulo": "Fahrenheit 451",
  "autor": "Ray Bradbury",
  "anio": 1953
}

###
PUT http://localhost:8080/libros/1
Content-Type: application/json

{
  "titulo": "El Quijote",
  "autor": "Miguel de Cervantes",
  "anio": 1605
}

###
DELETE http://localhost:8080/libros/4

### Capítulo 10 -- préstamos (relaciones JPA)
GET http://localhost:8080/prestamos

###
GET http://localhost:8080/prestamos/usuario/1

###
POST http://localhost:8080/prestamos/usuario/2/libro/3

###
PATCH http://localhost:8080/prestamos/1/devolucion
